### ISSUE TITLE
Create .unitypackage release

### ISSUE THREAD

**Issue by Bluscream** [JEM-Powered/JEM.Unity.DiscordRPC#1]
That would be nice, thank you :)

**Comment by TylkoDemon** [comment]
Unless you really want to use it, you need to clone this repo, add it to your project via package manager or whatever. Even adding it using package manager via git option should work. 

I don't think making a unitypackage is worth a bother as this repo has some experimental implementation that hasn't been touched in a year. But at the same time that got me thinking... do you need an improved version of such a fancy decor tool? I don't know if someone in 12months managed to created discord RPC extension for unity editor (and this is the sole reason why this project has been created xD). 
I may even put it on the asset store as free editor extension.

**Comment by Bluscream** [comment]
asset store would be fine with me aswell, i just want something that i can easily just throw in any project without many extra steps

**Comment by TylkoDemon** [comment]
Well then, when i find a bit of free time, i'll try to update this project and release .unitypackage at least here on github.
